# Generated by Django 5.2 on 2025-04-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Branch Code'),
        ),
    ]
