# Generated by Django 5.2 on 2025-04-24 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="branch",
            old_name="branch",
            new_name="city",
        ),
    ]
