# Generated by Django 5.2 on 2025-04-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_branch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, null=True, verbose_name='Branch Code'),
        ),
    ]
