# Generated by Django 5.2 on 2025-04-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_remove_branch_description_remove_branch_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Branch Code'),
        ),
    ]
