# Generated by Django 5.2 on 2025-04-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_alter_account_account_number_alter_branch_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
