# Generated by Django 5.2 on 2025-04-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_delete_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
