# Generated by Django 5.2 on 2025-04-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='cvv',
            new_name='_cvv',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='expiry_date',
            new_name='_expiry_date',
        ),
        migrations.AlterField(
            model_name='card',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
