# Generated by Django 5.2 on 2025-05-13 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcard",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="giftcard",
            name="expiry_date",
            field=models.DateField(
                default=datetime.datetime(
                    2030, 5, 12, 13, 8, 22, 781321, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
