# Generated by Django 5.2 on 2025-04-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_cvv_card__cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='_cvv',
            field=models.CharField(blank=True, db_column='cvv', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='_expiry_date',
            field=models.DateField(blank=True, db_column='expiry_date', null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='_pin',
            field=models.CharField(blank=True, db_column='pin', max_length=4, null=True),
        ),
    ]
