# Generated by Django 5.2 on 2025-05-14 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0003_alter_giftcard_balance_alter_giftcard_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcard",
            name="expiry_date",
            field=models.DateField(
                default=datetime.datetime(
                    2030, 5, 13, 10, 33, 16, 35778, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
