# Generated by Django 5.2 on 2025-04-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card__cvv_alter_card__expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
