# Generated by Django 5.2 on 2025-05-16 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0006_alter_giftcard_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcard",
            name="expiry_date",
            field=models.DateField(
                default=datetime.datetime(
                    2030, 5, 15, 6, 38, 54, 684099, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
