# Generated by Django 5.2 on 2025-05-16 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0007_alter_giftcard_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcard",
            name="expiry_date",
            field=models.DateField(
                default=datetime.datetime(
                    2030, 5, 15, 6, 39, 0, 856250, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
