# Generated by Django 5.2 on 2025-05-16 06:40

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0008_alter_giftcard_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcard",
            name="expiry_date",
            field=models.DateField(default=cards.models.expiry_date_default),
        ),
    ]
